-- Generated by Oracle SQL Developer Data Modeler 20.4.0.374.0801
--   at:        2021-04-28 09:30:48 SGT
--   site:      Oracle Database 12c
--   type:      Oracle Database 12c

set echo on
spool ad_schema_output.txt

DROP TABLE clinic CASCADE CONSTRAINTS;

DROP TABLE clinic_roving CASCADE CONSTRAINTS;

DROP TABLE drug CASCADE CONSTRAINTS;

DROP TABLE pet CASCADE CONSTRAINTS;

DROP TABLE pet_owner CASCADE CONSTRAINTS;

DROP TABLE pet_type CASCADE CONSTRAINTS;

DROP TABLE prescription CASCADE CONSTRAINTS;

DROP TABLE service CASCADE CONSTRAINTS;

DROP TABLE specialist CASCADE CONSTRAINTS;

DROP TABLE vet CASCADE CONSTRAINTS;

DROP TABLE visit CASCADE CONSTRAINTS;

-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE clinic (
    clinic_id       NUMBER(7) NOT NULL,
    clinic_name     VARCHAR2(30) NOT NULL,
    clinic_address  VARCHAR2(50) NOT NULL,
    clinic_phone    NUMBER(15) NOT NULL
);

COMMENT ON COLUMN clinic.clinic_id IS
    'clinic id';

COMMENT ON COLUMN clinic.clinic_name IS
    'clinic name';

COMMENT ON COLUMN clinic.clinic_address IS
    'clinic address';

COMMENT ON COLUMN clinic.clinic_phone IS
    'clinic phone number';

ALTER TABLE clinic ADD CONSTRAINT clinic_pk PRIMARY KEY ( clinic_id );

CREATE TABLE clinic_roving (
    clinic_id     NUMBER(7) NOT NULL,
    vet_id        NUMBER(7) NOT NULL,
    roving_count  NUMBER(3) NOT NULL
);

COMMENT ON COLUMN clinic_roving.clinic_id IS
    'clinic id';

COMMENT ON COLUMN clinic_roving.vet_id IS
    'vet id';

COMMENT ON COLUMN clinic_roving.roving_count IS
    'roving count';

ALTER TABLE clinic_roving ADD CONSTRAINT clinic_roving_pk PRIMARY KEY ( vet_id,
                                                                        clinic_id );

CREATE TABLE drug (
    drug_id           NUMBER(7) NOT NULL,
    drug_name         VARCHAR2(30) NOT NULL,
    drug_cost         NUMBER(10, 2) NOT NULL,
    drug_instruction  VARCHAR2(50) NOT NULL
);

COMMENT ON COLUMN drug.drug_id IS
    'drug id';

COMMENT ON COLUMN drug.drug_name IS
    'drug name';

COMMENT ON COLUMN drug.drug_cost IS
    'drug cost';

COMMENT ON COLUMN drug.drug_instruction IS
    'drug instruction';

ALTER TABLE drug ADD CONSTRAINT drug_pk PRIMARY KEY ( drug_id );

CREATE TABLE pet (
    animal_id         NUMBER(7) NOT NULL,
    animal_gender     VARCHAR2(10) NOT NULL,
    animal_type       VARCHAR2(50) NOT NULL,
    animal_birthdate  DATE NOT NULL,
    animal_deceased   CHAR(1) NOT NULL,
    owner_id          NUMBER(7) NOT NULL,
    animal_type_id    NUMBER(7) NOT NULL
);

ALTER TABLE pet
    ADD CONSTRAINT chk_animal_deceased CHECK ( animal_deceased IN ( 'N', 'Y' ) );

COMMENT ON COLUMN pet.animal_id IS
    'animal id';

COMMENT ON COLUMN pet.animal_gender IS
    'animal gender';

COMMENT ON COLUMN pet.animal_type IS
    'animal type';

COMMENT ON COLUMN pet.animal_birthdate IS
    'animal date of birth';

COMMENT ON COLUMN pet.animal_deceased IS
    'aniaml deceased';

COMMENT ON COLUMN pet.owner_id IS
    'owner id';

COMMENT ON COLUMN pet.animal_type_id IS
    'pet type id';

ALTER TABLE pet ADD CONSTRAINT pet_pk PRIMARY KEY ( animal_id );

CREATE TABLE pet_owner (
    owner_id            NUMBER(7) NOT NULL,
    owner_fname         VARCHAR2(50) NOT NULL,
    owner_lname         VARCHAR2(50) NOT NULL,
    owner_phone         VARCHAR2(15) NOT NULL,
    owner_add_street    VARCHAR2(50) NOT NULL,
    owner_add_town      VARCHAR2(50) NOT NULL,
    owner_add_postcode  NUMBER(10) NOT NULL,
    vet_id              NUMBER(7) NOT NULL
);

COMMENT ON COLUMN pet_owner.owner_id IS
    'owner id';

COMMENT ON COLUMN pet_owner.owner_fname IS
    'owner first name';

COMMENT ON COLUMN pet_owner.owner_lname IS
    'owner last name';

COMMENT ON COLUMN pet_owner.owner_phone IS
    'owner phone number';

COMMENT ON COLUMN pet_owner.owner_add_street IS
    'address street';

COMMENT ON COLUMN pet_owner.owner_add_town IS
    'address town';

COMMENT ON COLUMN pet_owner.owner_add_postcode IS
    'address postcode';

COMMENT ON COLUMN pet_owner.vet_id IS
    'vet id';

ALTER TABLE pet_owner ADD CONSTRAINT pet_owner_pk PRIMARY KEY ( owner_id );

CREATE TABLE pet_type (
    animal_type_id  NUMBER(7) NOT NULL,
    animal_type     VARCHAR2(20) NOT NULL
);

COMMENT ON COLUMN pet_type.animal_type_id IS
    'pet type id';

COMMENT ON COLUMN pet_type.animal_type IS
    'animal type';

ALTER TABLE pet_type ADD CONSTRAINT pet_type_pk PRIMARY KEY ( animal_type_id );

ALTER TABLE pet_type ADD CONSTRAINT un_animal_type UNIQUE ( animal_type );

CREATE TABLE prescription (
    prescription_id               NUMBER(7) NOT NULL,
    prescription_dose             NUMBER(5) NOT NULL,
    prescription_frequency_admin  NUMBER(5) NOT NULL,
    prescription_qty_supplied     NUMBER(10) NOT NULL,
    visit_datetime                DATE NOT NULL,
    drug_id                       NUMBER(7) NOT NULL,
    animal_id                     NUMBER(7) NOT NULL
);

COMMENT ON COLUMN prescription.prescription_id IS
    'prescription id';

COMMENT ON COLUMN prescription.prescription_dose IS
    'prescription dose';

COMMENT ON COLUMN prescription.prescription_frequency_admin IS
    'prescription frequency administration';

COMMENT ON COLUMN prescription.prescription_qty_supplied IS
    'quatity supplied';

COMMENT ON COLUMN prescription.visit_datetime IS
    'visit datetime';

COMMENT ON COLUMN prescription.drug_id IS
    'drug id';

COMMENT ON COLUMN prescription.animal_id IS
    'animal id';

ALTER TABLE prescription
    ADD CONSTRAINT prescription_pk PRIMARY KEY ( prescription_id,
                                                 visit_datetime,
                                                 drug_id,
                                                 animal_id );

CREATE TABLE service (
    service_code    NUMBER(7) NOT NULL,
    service_desc    VARCHAR2(100) NOT NULL,
    service_cost    NUMBER(10, 2) NOT NULL,
    visit_datetime  DATE NOT NULL,
    animal_id       NUMBER(7) NOT NULL
);

COMMENT ON COLUMN service.service_code IS
    'service code';

COMMENT ON COLUMN service.service_desc IS
    'service description';

COMMENT ON COLUMN service.service_cost IS
    'service cost';

COMMENT ON COLUMN service.visit_datetime IS
    'visit datetime';

COMMENT ON COLUMN service.animal_id IS
    'animal id';

ALTER TABLE service
    ADD CONSTRAINT service_pk PRIMARY KEY ( service_code,
                                            visit_datetime,
                                            animal_id );

ALTER TABLE service ADD CONSTRAINT uk_description UNIQUE ( service_desc );

CREATE TABLE specialist (
    specialist_id    NUMBER(7) NOT NULL,
    specialist_name  VARCHAR2(30) NOT NULL
);

COMMENT ON COLUMN specialist.specialist_id IS
    'specialist id';

COMMENT ON COLUMN specialist.specialist_name IS
    'specialist name';

ALTER TABLE specialist ADD CONSTRAINT specialist_pk PRIMARY KEY ( specialist_id );

CREATE TABLE vet (
    vet_id             NUMBER(7) NOT NULL,
    vet_givenname      VARCHAR2(20) NOT NULL,
    vet_familyname     VARCHAR2(20) NOT NULL,
    vet_phone          NUMBER(15) NOT NULL,
    vet_date_employed  DATE NOT NULL,
    specialist_id      NUMBER(7),
    clinic_id          NUMBER(7) NOT NULL
);

COMMENT ON COLUMN vet.vet_id IS
    'vet id';

COMMENT ON COLUMN vet.vet_givenname IS
    'vet given  name';

COMMENT ON COLUMN vet.vet_familyname IS
    'vet family name';

COMMENT ON COLUMN vet.vet_phone IS
    'vet phone';

COMMENT ON COLUMN vet.vet_date_employed IS
    'vet employed date';

COMMENT ON COLUMN vet.specialist_id IS
    'specialist id';

COMMENT ON COLUMN vet.clinic_id IS
    'clinic id';

ALTER TABLE vet ADD CONSTRAINT vet_pk PRIMARY KEY ( vet_id );

CREATE TABLE visit (
    animal_id             NUMBER(7) NOT NULL,
    visit_datetime        DATE NOT NULL,
    visit_length          NUMBER(5) NOT NULL,
    visit_notes           VARCHAR2(50) NOT NULL,
    visit_payment_method  VARCHAR2(10) NOT NULL,
    visit_payment_total   NUMBER(10, 2) NOT NULL,
    vet_id                NUMBER(7) NOT NULL,
    clinic_id             NUMBER(7) NOT NULL
);

COMMENT ON COLUMN visit.animal_id IS
    'animal id';

COMMENT ON COLUMN visit.visit_datetime IS
    'visit datetime';

COMMENT ON COLUMN visit.visit_length IS
    'visit length';

COMMENT ON COLUMN visit.visit_notes IS
    'visit notes';

COMMENT ON COLUMN visit.visit_payment_method IS
    'visit payment method';

COMMENT ON COLUMN visit.visit_payment_total IS
    'visit payment total';

COMMENT ON COLUMN visit.vet_id IS
    'vet id';

COMMENT ON COLUMN visit.clinic_id IS
    'clinic id';

ALTER TABLE visit ADD CONSTRAINT visit_pk PRIMARY KEY ( visit_datetime,
                                                        animal_id );

ALTER TABLE clinic_roving
    ADD CONSTRAINT clinic_roving FOREIGN KEY ( clinic_id )
        REFERENCES clinic ( clinic_id );

ALTER TABLE vet
    ADD CONSTRAINT clinic_vet FOREIGN KEY ( clinic_id )
        REFERENCES clinic ( clinic_id );

ALTER TABLE visit
    ADD CONSTRAINT clinic_visit FOREIGN KEY ( clinic_id )
        REFERENCES clinic ( clinic_id );

ALTER TABLE prescription
    ADD CONSTRAINT drug_prescription FOREIGN KEY ( drug_id )
        REFERENCES drug ( drug_id );

ALTER TABLE pet
    ADD CONSTRAINT owner_pet FOREIGN KEY ( owner_id )
        REFERENCES pet_owner ( owner_id );

ALTER TABLE visit
    ADD CONSTRAINT pet_visit FOREIGN KEY ( animal_id )
        REFERENCES pet ( animal_id );

ALTER TABLE vet
    ADD CONSTRAINT specialist_vet FOREIGN KEY ( specialist_id )
        REFERENCES specialist ( specialist_id );

ALTER TABLE pet
    ADD CONSTRAINT type_pet FOREIGN KEY ( animal_type_id )
        REFERENCES pet_type ( animal_type_id );

ALTER TABLE pet_owner
    ADD CONSTRAINT vet_owner FOREIGN KEY ( vet_id )
        REFERENCES vet ( vet_id );

ALTER TABLE clinic_roving
    ADD CONSTRAINT vet_roving FOREIGN KEY ( vet_id )
        REFERENCES vet ( vet_id );

ALTER TABLE visit
    ADD CONSTRAINT vet_visit FOREIGN KEY ( vet_id )
        REFERENCES vet ( vet_id );

ALTER TABLE prescription
    ADD CONSTRAINT visit_prescription FOREIGN KEY ( visit_datetime,
                                                    animal_id )
        REFERENCES visit ( visit_datetime,
                           animal_id );

ALTER TABLE service
    ADD CONSTRAINT visit_service FOREIGN KEY ( visit_datetime,
                                               animal_id )
        REFERENCES visit ( visit_datetime,
                           animal_id );

spool off
set echo off

-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            11
-- CREATE INDEX                             0
-- ALTER TABLE                             27
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- TSDP POLICY                              0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
